# conda environment configuration file
# for agkelpie project
name: agkelpie
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pip
  - pandas
  - pillow
  - pycocotools
  - scipy
  - scikit-image
  - scikit-learn
  - tensorboard
  - pytorch::pytorch=1.12.0
  - torchvision=0.13.0
  - torchaudio
  - nvidia::cudatoolkit=11.3
  - shapely
  - pylint
  - autopep8
  - flake8
  - pytorch-lightning
  - wandb
  - ipython
  - opencv
  - python-flatbuffers
  - boto3
  - onnx
  - onnxruntime

