# automatically generated by the FlatBuffers compiler, do not modify

# namespace: agKelpieImage

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AgKelpieImage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AgKelpieImage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAgKelpieImage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AgKelpieImage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AgKelpieImage
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # AgKelpieImage
    def Image(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from agKelpieImage.Image import Image
            obj = Image()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def Start(builder): builder.StartObject(2)
def AgKelpieImageStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddTimestamp(builder, timestamp): builder.PrependInt64Slot(0, timestamp, 0)
def AgKelpieImageAddTimestamp(builder, timestamp):
    """This method is deprecated. Please switch to AddTimestamp."""
    return AddTimestamp(builder, timestamp)
def AddImage(builder, image): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(image), 0)
def AgKelpieImageAddImage(builder, image):
    """This method is deprecated. Please switch to AddImage."""
    return AddImage(builder, image)
def End(builder): return builder.EndObject()
def AgKelpieImageEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)